# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Indie Glue
email: indiegluedev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website and dev blog for Indie Glue game development
baseurl: "/jekyll-gameblog-template" # the subpath of your site, e.g. /blog
url: "http://indieglue.com" # the base hostname & protocol for your site
twitter_username: indieglue
github_username:  nikrich

# Build settings
markdown: kramdown
